---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: privatebin-tls
spec:
  secretName: privatebin-tls
  dnsNames:
  - paste.gduque.fr
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
