---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard-tls
  namespace: traefik
spec:
  secretName: traefik-dashboard-tls
  dnsNames:
  - traefik.gduque.fr
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
