---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--entrypoints.websecure.http.middlewares=traefik-security-headers@kubernetescrd"
    # ports:
    #   web:
    #     redirectTo: websecure
    providers:
      kubernetesCRD:
        allowCrossNamespace: true

