---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: privatebin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitea.com/gduque/gduque.fr.git
    targetRevision: HEAD
    path: privatebin
  destination:
    server: https://kubernetes.default.svc
    namespace: privatebin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true