---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argo-cd
  namespace: kube-system
spec:
  chart: argo-cd
  repo: "https://argoproj.github.io/argo-helm"
  targetNamespace: argo-cd
  valuesContent: |-
    server:
      ingress:
        https: true
        annotations:
          kubernetes.io/tls-acme: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-master-forward-auth@kubernetescrd"
        enabled: "true"
        hosts:
          - "argocd.gduque.fr"
        tls:
          - hosts:
            - "argocd.gduque.fr"
            secretName: "argocd-tls"

