---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  version: 1.5.4
  repo: "https://charts.jetstack.io"
  targetNamespace: cert-manager
  set:
    installCRDs: "true"
  valuesContent: |-
    ingressShim:
      defaultIssuerName: "letsencrypt-staging"
      defaultIssuerKind: "ClusterIssuer"
      defaultIssuerGroup: "cert-manager.io"

